import { useState, useEffect, useCallback, useRef } from 'react'
import NewspaperHeader from './components/NewspaperHeader'
import EventSelector from './components/EventSelector'
import HeadlineCard from './components/HeadlineCard'
import LoadingSpinner from './components/LoadingSpinner'

// ── Constants ──────────────────────────────────────────────────────────────
const API_BASE = import.meta.env.VITE_API_URL || 'http://localhost:8000'

const EDITION_LABELS = {
  POLITICS: '🏛️ Political Dispatch',
  TECH:     '💻 Technology Review',
  SCIENCE:  '🔬 Science & Discovery',
  WORLD:    '🌍 World Affairs',
  ECONOMY:  '📈 Economic Report',
  CULTURE:  '🎭 Arts & Culture',
}

const FUN_FACTS = [
  "In quantum mechanics, all possible histories exist simultaneously.",
  "The butterfly effect means even small changes can alter entire timelines.",
  "Physicists estimate there may be 10^500 parallel universes.",
  "Every decision you make spawns a new branch of reality.",
  "Some physicists believe alternate timelines are mathematically inevitable.",
  "The many-worlds interpretation suggests every outcome actually happens.",
]

// ── Utility ────────────────────────────────────────────────────────────────
const groupByCategory = (headlines) => {
  return headlines.reduce((acc, h) => {
    const cat = h.category?.toUpperCase() || 'WORLD'
    if (!acc[cat]) acc[cat] = []
    acc[cat].push(h)
    return acc
  }, {})
}

const getShareText = (event, headlines) => {
  const top3 = headlines.slice(0, 3).map(h => `• ${h.headline}`).join('\n')
  return `📰 Parallel Universe News\n\nDivergence: "${event}"\n\n${top3}\n\nGenerated by The Multiverse Courier`
}

// ── History item component ─────────────────────────────────────────────────
const HistoryItem = ({ item, onReload, isActive }) => (
  <button
    onClick={() => onReload(item)}
    className={`
      w-full text-left px-3 py-2 border-b border-gray-100
      hover:bg-gray-50 transition-colors duration-150
      ${isActive ? 'bg-accent-light border-l-2 border-l-accent' : ''}
    `}
  >
    <p className="byline text-xs text-ink truncate">{item.event}</p>
    <p className="byline text-xs text-ink-muted mt-0.5">{item.universeId} · {item.timestamp}</p>
  </button>
)

// ── Stats bar component ────────────────────────────────────────────────────
const StatsBar = ({ headlines, generationTime }) => {
  const categories = [...new Set(headlines.map(h => h.category?.toUpperCase()))]
  const outlets    = [...new Set(headlines.map(h => h.outlet))]

  return (
    <div className="max-w-6xl mx-auto px-4 mb-6">
      <div className="bg-ink text-newsprint px-4 py-2 flex flex-wrap items-center gap-4 text-xs font-mono animate-fadeIn">
        <span>📰 {headlines.length} Headlines</span>
        <span className="text-gray-400">·</span>
        <span>📡 {outlets.length} Outlets</span>
        <span className="text-gray-400">·</span>
        <span>🗂 {categories.length} Categories</span>
        <span className="text-gray-400">·</span>
        <span>⚡ Generated in {generationTime}s</span>
        <span className="text-gray-400">·</span>
        <span className="text-accent">✦ Alternate Timeline Verified</span>
      </div>
    </div>
  )
}

// ── Toast notification ─────────────────────────────────────────────────────
const Toast = ({ message, type = 'info', onClose }) => {
  useEffect(() => {
    const t = setTimeout(onClose, 3000)
    return () => clearTimeout(t)
  }, [onClose])

  const colors = {
    info:    'bg-ink text-newsprint',
    success: 'bg-green-800 text-white',
    error:   'bg-accent text-white',
  }

  return (
    <div className={`
      fixed bottom-6 right-6 z-50 px-4 py-3 shadow-xl
      flex items-center gap-3 animate-fadeInUp
      ${colors[type]}
    `}>
      <span className="text-sm font-medium">{message}</span>
      <button onClick={onClose} className="text-xs opacity-60 hover:opacity-100">✕</button>
    </div>
  )
}

// ── Sidebar ────────────────────────────────────────────────────────────────
const Sidebar = ({ history, currentEvent, onReload, funFact, isOpen, onClose }) => (
  <>
    {/* Backdrop */}
    {isOpen && (
      <div
        className="fixed inset-0 bg-black bg-opacity-30 z-30 lg:hidden"
        onClick={onClose}
      />
    )}

    <aside className={`
      fixed top-0 right-0 h-full w-72 bg-newsprint border-l border-gray-300
      z-40 transform transition-transform duration-300 ease-in-out
      flex flex-col shadow-2xl
      ${isOpen ? 'translate-x-0' : 'translate-x-full'}
      lg:relative lg:translate-x-0 lg:shadow-none lg:z-auto
    `}>
      {/* Sidebar header */}
      <div className="px-4 py-3 border-b-2 border-ink flex items-center justify-between">
        <h3 className="playfair font-bold text-sm">Timeline Archive</h3>
        <button
          onClick={onClose}
          className="lg:hidden byline text-ink-muted hover:text-ink"
        >✕</button>
      </div>

      {/* History list */}
      <div className="flex-1 overflow-y-auto">
        {history.length === 0 ? (
          <div className="px-4 py-6 text-center">
            <p className="text-2xl mb-2">🌌</p>
            <p className="byline text-ink-muted text-xs">
              No timelines explored yet.<br />Generate your first universe!
            </p>
          </div>
        ) : (
          <div>
            <p className="byline text-ink-muted text-xs px-3 py-2 border-b border-gray-100">
              {history.length} timeline{history.length !== 1 ? 's' : ''} explored
            </p>
            {history.map((item, i) => (
              <HistoryItem
                key={i}
                item={item}
                onReload={onReload}
                isActive={item.event === currentEvent}
              />
            ))}
          </div>
        )}
      </div>

      {/* Fun fact footer */}
      <div className="border-t border-gray-300 px-4 py-4 bg-newsprint-dark">
        <p className="byline text-xs text-accent mb-1 tracking-widest">✦ Did You Know?</p>
        <p className="text-xs text-ink-muted italic font-serif leading-relaxed">
          "{funFact}"
        </p>
      </div>
    </aside>
  </>
)

// ── View mode toggle ───────────────────────────────────────────────────────
const ViewToggle = ({ mode, onChange }) => (
  <div className="flex items-center gap-1 border border-gray-300 p-0.5 bg-white">
    {[
      { id: 'grid',     icon: '⊞', label: 'Grid' },
      { id: 'featured', icon: '◈', label: 'Featured' },
      { id: 'category', icon: '≡', label: 'By Category' },
    ].map(v => (
      <button
        key={v.id}
        onClick={() => onChange(v.id)}
        title={v.label}
        className={`
          px-2 py-1 text-xs byline transition-colors
          ${mode === v.id ? 'bg-ink text-newsprint' : 'text-ink-muted hover:text-ink'}
        `}
      >
        {v.icon} {v.label}
      </button>
    ))}
  </div>
)

// ── Main App ───────────────────────────────────────────────────────────────
export default function App() {
  const [headlines, setHeadlines]         = useState([])
  const [currentEvent, setCurrentEvent]   = useState('')
  const [universeId, setUniverseId]       = useState('')
  const [isLoading, setIsLoading]         = useState(false)
  const [error, setError]                 = useState('')
  const [history, setHistory]             = useState(() => {
    try { return JSON.parse(localStorage.getItem('pun_history') || '[]') }
    catch { return [] }
  })
  const [viewMode, setViewMode]           = useState('grid')
  const [toast, setToast]                 = useState(null)
  const [sidebarOpen, setSidebarOpen]     = useState(false)
  const [generationTime, setGenerationTime] = useState(null)
  const [funFact]                         = useState(
    () => FUN_FACTS[Math.floor(Math.random() * FUN_FACTS.length)]
  )
  const [healthStatus, setHealthStatus]   = useState(null)
  const [filterCategory, setFilterCategory] = useState('ALL')

  const headlinesRef = useRef(null)
  const abortRef     = useRef(null)

  // ── Check backend health on mount ────────────────────────────────────────
  useEffect(() => {
    const checkHealth = async () => {
      try {
        const res = await fetch(`${API_BASE}/health`, { signal: AbortSignal.timeout(5000) })
        const data = await res.json()
        setHealthStatus(data)
        if (data.status === 'error') {
          showToast('⚠ Backend unreachable — is Ollama running?', 'error')
        } else if (!data.model_loaded) {
          showToast('⚠ Model not loaded — run: ollama pull mistral:7b-instruct', 'error')
        }
      } catch {
        setHealthStatus({ status: 'error' })
      }
    }
    checkHealth()
  }, [])

  // ── Persist history to localStorage ──────────────────────────────────────
  useEffect(() => {
    try { localStorage.setItem('pun_history', JSON.stringify(history.slice(0, 20))) }
    catch {}
  }, [history])

  // ── Toast helper ──────────────────────────────────────────────────────────
  const showToast = useCallback((message, type = 'info') => {
    setToast({ message, type, id: Date.now() })
  }, [])

  // ── Generate headlines ────────────────────────────────────────────────────
  const handleGenerate = useCallback(async (event) => {
    // Cancel any in-flight request
    if (abortRef.current) abortRef.current.abort()
    abortRef.current = new AbortController()

    setIsLoading(true)
    setError('')
    setHeadlines([])
    setFilterCategory('ALL')
    const startTime = Date.now()

    try {
      const res = await fetch(`${API_BASE}/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ event }),
        signal: abortRef.current.signal,
      })

      if (!res.ok) {
        const errData = await res.json().catch(() => ({}))
        throw new Error(errData.detail || `Server error: ${res.status}`)
      }

      const data = await res.json()
      const elapsed = ((Date.now() - startTime) / 1000).toFixed(1)

      setHeadlines(data.headlines)
      setCurrentEvent(data.event)
      setUniverseId(data.universe_id)
      setGenerationTime(elapsed)

      // Add to history
      const historyItem = {
        event: data.event,
        universeId: data.universe_id,
        headlines: data.headlines,
        timestamp: new Date().toLocaleTimeString(),
        generationTime: elapsed,
      }
      setHistory(prev => [historyItem, ...prev.filter(h => h.event !== data.event)].slice(0, 20))

      showToast(`✦ ${data.headlines.length} headlines from ${data.universe_id}`, 'success')

      // Scroll to headlines
      setTimeout(() => {
        headlinesRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })
      }, 100)

    } catch (err) {
      if (err.name === 'AbortError') return
      const msg = err.message.includes('fetch')
        ? 'Cannot reach backend. Make sure FastAPI is running on port 8000.'
        : err.message
      setError(msg)
      showToast(`✕ ${msg}`, 'error')
    } finally {
      setIsLoading(false)
    }
  }, [showToast])

  // ── Reload from history ───────────────────────────────────────────────────
  const handleReload = useCallback((item) => {
    setHeadlines(item.headlines)
    setCurrentEvent(item.event)
    setUniverseId(item.universeId)
    setGenerationTime(item.generationTime)
    setFilterCategory('ALL')
    setSidebarOpen(false)
    showToast(`✦ Restored ${item.universeId}`, 'info')
    setTimeout(() => {
      headlinesRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })
    }, 100)
  }, [showToast])

  // ── Share ─────────────────────────────────────────────────────────────────
  const handleShare = useCallback(async () => {
    const text = getShareText(currentEvent, headlines)
    try {
      if (navigator.share) {
        await navigator.share({ title: 'Parallel Universe News', text })
      } else {
        await navigator.clipboard.writeText(text)
        showToast('✓ Copied to clipboard!', 'success')
      }
    } catch {
      showToast('Could not share — try copying manually.', 'error')
    }
  }, [currentEvent, headlines, showToast])

  // ── Clear history ─────────────────────────────────────────────────────────
  const handleClearHistory = () => {
    setHistory([])
    showToast('Timeline archive cleared.', 'info')
  }

  // ── Filtered + display headlines ──────────────────────────────────────────
  const filteredHeadlines = filterCategory === 'ALL'
    ? headlines
    : headlines.filter(h => h.category?.toUpperCase() === filterCategory)

  const categories = [...new Set(headlines.map(h => h.category?.toUpperCase()).filter(Boolean))]

  // ── Render: Grid view ─────────────────────────────────────────────────────
  const renderGrid = () => (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      {filteredHeadlines.map((h, i) => (
        <HeadlineCard key={i} {...h} index={i} featured={i === 0 && filterCategory === 'ALL'} />
      ))}
    </div>
  )

  // ── Render: Featured view ─────────────────────────────────────────────────
  const renderFeatured = () => {
    const [lead, ...rest] = filteredHeadlines
    return (
      <div className="space-y-4">
        {lead && (
          <div className="lg:col-span-3">
            <HeadlineCard {...lead} index={0} featured />
          </div>
        )}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {rest.map((h, i) => (
            <HeadlineCard key={i + 1} {...h} index={i + 1} />
          ))}
        </div>
      </div>
    )
  }

  // ── Render: Category view ─────────────────────────────────────────────────
  const renderByCategory = () => {
    const grouped = groupByCategory(filteredHeadlines)
    return (
      <div className="space-y-8">
        {Object.entries(grouped).map(([cat, items]) => (
          <div key={cat}>
            <div className="flex items-center gap-3 mb-4">
              <h3 className="playfair font-bold text-lg">
                {EDITION_LABELS[cat] || cat}
              </h3>
              <hr className="flex-1 border-t border-gray-300" />
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {items.map((h, i) => (
                <HeadlineCard key={i} {...h} index={i} />
              ))}
            </div>
          </div>
        ))}
      </div>
    )
  }

  // ── Render: Empty state ───────────────────────────────────────────────────
  const renderEmptyState = () => (
    <div className="text-center py-20 animate-fadeIn">
      <div className="text-6xl mb-4">🌌</div>
      <h2 className="playfair text-2xl font-bold mb-2">
        The Multiverse Awaits
      </h2>
      <p className="byline text-ink-muted text-sm max-w-md mx-auto leading-relaxed">
        Choose a divergence point above and our multiverse correspondents
        will report back with today's headlines from that alternate timeline.
      </p>
      <div className="mt-8 ornament-divider max-w-xs mx-auto">
        <span className="byline text-xs">✦</span>
      </div>
      <p className="byline text-xs text-ink-muted mt-4 italic">
        "{funFact}"
      </p>
    </div>
  )

  // ── JSX ───────────────────────────────────────────────────────────────────
  return (
    <div className="min-h-screen flex flex-col">

      {/* ── Newspaper Header ─────────────────────────────────────────────── */}
      <NewspaperHeader event={currentEvent} universeId={universeId} />

      {/* ── Health warning banner ─────────────────────────────────────────── */}
      {healthStatus?.status === 'error' && (
        <div className="bg-accent text-white text-center py-2 px-4 text-xs font-medium animate-fadeIn">
          ⚠ Backend unreachable — make sure FastAPI + Ollama are running locally
        </div>
      )}
      {healthStatus?.status === 'degraded' && (
        <div className="bg-yellow-700 text-white text-center py-2 px-4 text-xs font-medium animate-fadeIn">
          ⚠ Ollama running but mistral:7b-instruct not loaded — run: ollama pull mistral:7b-instruct
        </div>
      )}

      {/* ── Main layout ──────────────────────────────────────────────────── */}
      <div className="flex flex-1 max-w-screen-2xl mx-auto w-full">

        {/* ── Content area ───────────────────────────────────────────────── */}
        <main className="flex-1 min-w-0">

          {/* Event selector */}
          <EventSelector onGenerate={handleGenerate} isLoading={isLoading} />

          {/* Error box */}
          {error && (
            <div className="max-w-6xl mx-auto px-4 mb-6">
              <div className="error-box animate-fadeIn">
                <strong>⚠ Generation Failed:</strong> {error}
                <button
                  onClick={() => setError('')}
                  className="ml-3 byline text-xs underline"
                >
                  Dismiss
                </button>
              </div>
            </div>
          )}

          {/* Loading state */}
          {isLoading && (
            <div className="max-w-6xl mx-auto px-4">
              <LoadingSpinner />
            </div>
          )}

          {/* Headlines section */}
          {!isLoading && headlines.length > 0 && (
            <div ref={headlinesRef} className="max-w-6xl mx-auto px-4 pb-16">

              {/* Stats bar */}
              <StatsBar headlines={headlines} generationTime={generationTime} />

              {/* Toolbar */}
              <div className="flex flex-wrap items-center justify-between gap-3 mb-6">

                {/* View toggle */}
                <ViewToggle mode={viewMode} onChange={setViewMode} />

                {/* Category filter */}
                <div className="flex flex-wrap gap-1.5">
                  <button
                    onClick={() => setFilterCategory('ALL')}
                    className={`preset-chip text-xs ${filterCategory === 'ALL' ? 'bg-ink text-newsprint border-ink' : ''}`}
                  >
                    All
                  </button>
                  {categories.map(cat => (
                    <button
                      key={cat}
                      onClick={() => setFilterCategory(cat)}
                      className={`preset-chip text-xs ${filterCategory === cat ? 'bg-ink text-newsprint border-ink' : ''}`}
                    >
                      {cat}
                    </button>
                  ))}
                </div>

                {/* Share + Sidebar toggle */}
                <div className="flex items-center gap-2">
                  <button
                    onClick={handleShare}
                    className="generate-btn py-1.5 px-3 text-xs"
                    title="Share headlines"
                  >
                    ↑ Share
                  </button>
                  <button
                    onClick={() => setSidebarOpen(true)}
                    className="generate-btn py-1.5 px-3 text-xs lg:hidden"
                  >
                    ☰ Archive
                  </button>
                </div>
              </div>

              {/* No results after filter */}
              {filteredHeadlines.length === 0 && (
                <div className="text-center py-12">
                  <p className="byline text-ink-muted">No headlines in this category.</p>
                </div>
              )}

              {/* Headline views */}
              {filteredHeadlines.length > 0 && (
                <>
                  {viewMode === 'grid'     && renderGrid()}
                  {viewMode === 'featured' && renderFeatured()}
                  {viewMode === 'category' && renderByCategory()}
                </>
              )}

              {/* Footer ornament */}
              <div className="ornament-divider mt-12">
                <span className="byline text-xs">✦ End of Transmission ✦</span>
              </div>
              <p className="text-center byline text-xs text-ink-muted mt-2">
                All articles are AI-generated fiction from alternate timelines.
                Any resemblance to actual events is a multiverse coincidence.
              </p>
            </div>
          )}

          {/* Empty state */}
          {!isLoading && headlines.length === 0 && !error && renderEmptyState()}
        </main>

        {/* ── Sidebar (desktop always visible) ───────────────────────────── */}
        <div className="hidden lg:block w-72 shrink-0 border-l border-gray-300 sticky top-0 h-screen overflow-hidden">
          <div className="h-full flex flex-col">
            {/* Sidebar header */}
            <div className="px-4 py-3 border-b-2 border-ink flex items-center justify-between">
              <h3 className="playfair font-bold text-sm">Timeline Archive</h3>
              {history.length > 0 && (
                <button
                  onClick={handleClearHistory}
                  className="byline text-xs text-ink-muted hover:text-accent"
                >
                  Clear
                </button>
              )}
            </div>

            {/* History */}
            <div className="flex-1 overflow-y-auto">
              {history.length === 0 ? (
                <div className="px-4 py-6 text-center">
                  <p className="text-2xl mb-2">🌌</p>
                  <p className="byline text-ink-muted text-xs">
                    No timelines explored yet.<br />Generate your first universe!
                  </p>
                </div>
              ) : (
                <div>
                  <p className="byline text-ink-muted text-xs px-3 py-2 border-b border-gray-100">
                    {history.length} timeline{history.length !== 1 ? 's' : ''} explored
                  </p>
                  {history.map((item, i) => (
                    <HistoryItem
                      key={i}
                      item={item}
                      onReload={handleReload}
                      isActive={item.event === currentEvent}
                    />
                  ))}
                </div>
              )}
            </div>

            {/* Fun fact */}
            <div className="border-t border-gray-300 px-4 py-4">
              <p className="byline text-xs text-accent mb-1 tracking-widest">✦ Did You Know?</p>
              <p className="text-xs text-ink-muted italic font-serif leading-relaxed">
                "{funFact}"
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* ── Mobile sidebar ───────────────────────────────────────────────── */}
      <div className="lg:hidden">
        <Sidebar
          history={history}
          currentEvent={currentEvent}
          onReload={handleReload}
          funFact={funFact}
          isOpen={sidebarOpen}
          onClose={() => setSidebarOpen(false)}
        />
      </div>

      {/* ── Toast ────────────────────────────────────────────────────────── */}
      {toast && (
        <Toast
          key={toast.id}
          message={toast.message}
          type={toast.type}
          onClose={() => setToast(null)}
        />
      )}
    </div>
  )
}